### ISSUE TITLE
system time based API

### ISSUE THREAD

**Issue by mururu** [nurse/strptime#3]
`Time.strptime` uses the current system time as base time, but `Strptime#exec` dosen't.

```
Time.strptime("2", "%d") #=> 2015-08-02 00:00:00 +0900
Strptime.new("%d").exec("2") #=> 1970-01-02 00:00:00 +0000
```

I need an API which uses the current system time as base time. Is it possible? Or does it cause a serious performance degradation?

**Comment by nurse** [comment]
It sounds reasonable, and gettimeofday of modern OS (RHEL6+) is fast enough. (it should use clock_gettime if exist)
gmtime(3) or localtime(3) are also slow but you can cache the value if the given time_t is equal or near enough.

If you create a patch, I'll merge it.
If you show a benchmark which says gmtime/localtime cost is low, such trick is not required.

**Comment by mururu** [comment]
Thanks. I'll try create a patch tomorrow.
