### ISSUE TITLE
Check given format is supported or not

### ISSUE THREAD

**Issue by mururu** [nurse/strptime#5]
Strptime doesn't support all formats which is supported by `Time.strptime`. It is OK for my use case (except %b for apache access log, I will send a pull request later).
But I want to know given format string is valid or not on Strptime gem to fall back to `Time.strptime`.
My ideas are

* `Strptime.valid_format?(fmt)`

```
> Strptime.valid_format?("%s") => false
```

* raise error

```
> Strptime.new("%s") => ArgumentError: invalid format %s
```

Any thoughts?

**Comment by mururu** [comment]
Ah, sorry. `%b` is already supported.

**Comment by nurse** [comment]
A patch to support other specifiers is welcome until it is in standard.

**Comment by nurse** [comment]
Ah, raising error is acceptable.

**Comment by mururu** [comment]
> Ah, raising error is acceptable.

Thank you. I will do that way.
